### PR TITLE
Snoop version implemented

### PR DESCRIPTION
**Pull request by ivargrimstad**
This fixes arungupta/microservices#21

Since I had to make small changes in the everest app to test the integration through snoop, I did this in a separate branch.

### CODE REVIEW

**Comment by ivargrimstad** [comment]
You're right. The data-source element in the persistence.xml files does not need to be there. For some reason Wildfly complained when I did not have it there. Should not be needed. Just forgot to remove it from the commit.

The @EnableSnoopClient annotation can stay even if the server is not running. It will log that it tried to connect and failed though.

**Comment by arun-gupta** [comment]
Can you amend the PR?

**Comment by ivargrimstad** [comment]
The log will look like this if the snoop-service is not running: 
19:22:50,006 CONFIG [eu.agilejava.snoop](EJB default - 7) Sending message: {"applicationName":"order","applicationHome":"http://localhost:8080/order/resources","applicationServiceRoot":"order"}
19:22:50,015 WARNING [eu.agilejava.snoop](EJB default - 3) Connection refused

**Comment by arun-gupta** [comment]
Can you add a Snoop container as well?

**Comment by ivargrimstad** [comment]
I pushed one to docker hub today called ivargrimstad/snoop-service
https://registry.hub.docker.com/u/ivargrimstad/snoop-service/

The latest war is also available in my nexus (running on openshift of course :))
http://nexus.agilejava.eu/nexus/index.html#nexus-search;quick~snoop-service

**Comment by arun-gupta** [comment]
Add the instructions to the doc here?

**Comment by arun-gupta** [comment]
Thanks a lot @ivargrimstad, now merged!

**Comment by ivargrimstad** [comment]
Brilliant! Had great fun :)

**Comment by arun-gupta** [comment]
Refactored the code as well, and I think its much cleaner now.

**Comment by ivargrimstad** [comment]
Looks great!

**Pull request merged**
